version: "2"
services:
  rest-backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - backend-postgres

  front:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"