version: "2"
services:
#  backend:
#    container_name: monolith
#    build:
#      context: backend
#      dockerfile: Dockerfile
#    network_mode: host
#    volumes:
#      - ./backend/m2:/root/.m2
#    depends_on:
#      - backend-postgres

  front:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"